name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: waka-box
    runs-on: ubuntu-latest
    steps:
      - uses: matchai/waka-box@v5.0.0
